package executor

type test struct {
	cmds, res []string
}

var testParkCar = []test{
	{
		cmds: []string{"create_parking_lot 5",
			"park TY90F0 RED",
			"park XY71Q0 BLUE",
			"park WY54P0 GREEN",
			"park UY39F0 RED",
			"park TR10F9 WHITE",
			"park PY90E5 RED",
			"park DT74Y0 YELLOW"},
		res: []string{"",
			"",
			"",
			"",
			"",
			"",
			"",
			""},
	},
	{
		cmds: []string{"create_parking_lot 5",
			"park TY90F0 RED",
			"park XY71Q0 BLUE",
			"park UY39F0 RED",
			"park UY39F0 RED",
			"park TR10F9 WHITE",
			"park PY90E5 RED",
			"park DT74Y0 YELLOW"},
		res: []string{"",
			"",
			"",
			"Already in slot no 3",
			"",
			"",
			"No slot available :("},
	},
	{
		cmds: []string{"park TY90F0 RED",
			"park XY71Q0 BLUE",
			"park UY39F0 RED",
			"park UY39F0 RED",
			"park TR10F9 WHITE",
			"park PY90E5 RED",
			"park DT74Y0 YELLOW"},
		res: []string{"No slot available :(",
			"No slot available :(",
			"No slot available :(",
			"No slot available :(",
			"No slot available :(",
			"No slot available :(",
			"No slot available :("},
	},
}

var testLeaveParking = []test{
	{
		cmds: []string{"create_parking_lot 5",
			"park TY90F0 RED",
			"park XY71Q0 BLUE",
			"park WY54P0 GREEN",
			"park UY39F0 RED",
			"leave 2",
			"park TR10F9 WHITE",
			"park PY90E5 RED",
			"leave 5"},
		res: []string{"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""},
	},
	{
		cmds: []string{"create_parking_lot 5",
			"park TY90F0 RED",
			"leave 8",
			"park XY71Q0 BLUE",
			"park WY54P0 GREEN",
			"park UY39F0 RED",
			"leave 5",
			"park TR10F9 WHITE",
			"leave 5"},
		res: []string{"",
			"",
			"Invalid slot no :(",
			"",
			"",
			"",
			"No vehicle found in slot 5",
			"",
			""},
	},
}

var testPrintStatus = []test{
	{
		cmds: []string{"create_parking_lot 5",
			"park TY90F0 RED",
			"park XY71Q0 BLUE",
			"park WY54P0 GREEN",
			"park UY39F0 RED",
			"leave 2",
			"park TR10F9 WHITE",
			"status",
			"park PY90E5 RED",
			"leave 5",
			"status"},
		res: []string{"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""},
	},
	{
		cmds: []string{"create_parking_lot 5",
			"park TY90F0 RED",
			"park XY71Q0 BLUE",
			"park WY54P0 GREEN",
			"park UY39F0 RED",
			"leave 2",
			"park TR10F9 WHITE",
			"status",
			"park PY90E5 RED",
			"leave 5",
			"park DT74Y0 YELLOW",
			"registration_numbers_for_cars_with_colour RED",
			"slot_numbers_for_cars_with_colour GREEN",
			"slot_number_for_registration_number TY90F0"},
		res: []string{"", "", "", "", "", "", "", "status", "", "", "", "reg num", "slot nums", "slot num"},
	},
}

var testFindRegNumsByColor = []test{
	{
		cmds: []string{"create_parking_lot 5",
			"park TY90F0 RED",
			"park XY71Q0 BLUE",
			"park WY54P0 GREEN",
			"park UY39F0 RED",
			"leave 2",
			"park TR10F9 WHITE",
			"status",
			"park PY90E5 RED",
			"leave 5",
			"park DT74Y0 YELLOW",
			"registration_numbers_for_cars_with_colour RED",
			"slot_numbers_for_cars_with_colour GREEN",
			"slot_number_for_registration_number TY90F0"},
		res: []string{"", "", "", "", "", "", "", "status", "", "", "", "reg num", "slot nums", "slot num"},
	},
	{
		cmds: []string{"create_parking_lot 5",
			"park TY90F0 RED",
			"park XY71Q0 BLUE",
			"park WY54P0 GREEN",
			"park UY39F0 RED",
			"leave 2",
			"park TR10F9 WHITE",
			"status",
			"park PY90E5 RED",
			"leave 5",
			"park DT74Y0 YELLOW",
			"registration_numbers_for_cars_with_colour RED",
			"slot_numbers_for_cars_with_colour GREEN",
			"slot_number_for_registration_number TY90F0"},
		res: []string{"", "", "", "", "", "", "", "status", "", "", "", "reg num", "slot nums", "slot num"},
	},
}

var testFindSlotNumsByColor = []test{
	{
		cmds: []string{"create_parking_lot 5",
			"park TY90F0 RED",
			"park XY71Q0 BLUE",
			"park WY54P0 GREEN",
			"park UY39F0 RED",
			"leave 2",
			"park TR10F9 WHITE",
			"status",
			"park PY90E5 RED",
			"leave 5",
			"park DT74Y0 YELLOW",
			"registration_numbers_for_cars_with_colour RED",
			"slot_numbers_for_cars_with_colour GREEN",
			"slot_number_for_registration_number TY90F0"},
		res: []string{"", "", "", "", "", "", "", "status", "", "", "", "reg num", "slot nums", "slot num"},
	},
	{
		cmds: []string{"create_parking_lot 5",
			"park TY90F0 RED",
			"park XY71Q0 BLUE",
			"park WY54P0 GREEN",
			"park UY39F0 RED",
			"leave 2",
			"park TR10F9 WHITE",
			"status",
			"park PY90E5 RED",
			"leave 5",
			"park DT74Y0 YELLOW",
			"registration_numbers_for_cars_with_colour RED",
			"slot_numbers_for_cars_with_colour GREEN",
			"slot_number_for_registration_number TY90F0"},
		res: []string{"", "", "", "", "", "", "", "status", "", "", "", "reg num", "slot nums", "slot num"},
	},
}

var testFindSlotNoByRegNum = []test{
	{
		cmds: []string{"create_parking_lot 5",
			"park TY90F0 RED",
			"park XY71Q0 BLUE",
			"park WY54P0 GREEN",
			"park UY39F0 RED",
			"leave 2",
			"park TR10F9 WHITE",
			"status",
			"park PY90E5 RED",
			"leave 5",
			"park DT74Y0 YELLOW",
			"registration_numbers_for_cars_with_colour RED",
			"slot_numbers_for_cars_with_colour GREEN",
			"slot_number_for_registration_number TY90F0"},
		res: []string{"", "", "", "", "", "", "", "status", "", "", "", "reg num", "slot nums", "slot num"},
	},
	{
		cmds: []string{"create_parking_lot 5",
			"park TY90F0 RED",
			"park XY71Q0 BLUE",
			"park WY54P0 GREEN",
			"park UY39F0 RED",
			"leave 2",
			"park TR10F9 WHITE",
			"status",
			"park PY90E5 RED",
			"leave 5",
			"park DT74Y0 YELLOW",
			"registration_numbers_for_cars_with_colour RED",
			"slot_numbers_for_cars_with_colour GREEN",
			"slot_number_for_registration_number TY90F0"},
		res: []string{"", "", "", "", "", "", "", "status", "", "", "", "reg num", "slot nums", "slot num"},
	},
}
